const ERROR_CODES = Object.freeze({
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  FORBIDDEN: "FORBIDDEN",
  USER_PROFILE_NOT_FOUND: "USER_PROFILE_NOT_FOUND",
  USER_DISABLED: "USER_DISABLED",
  PROPERTY_ACCESS_DENIED: "PROPERTY_ACCESS_DENIED",
  PROPERTY_ID_REQUIRED: "PROPERTY_ID_REQUIRED",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
});

module.exports = { ERROR_CODES };
