const ERROR_CODES = Object.freeze({
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_TOKEN: "INVALID_TOKEN",
  FORBIDDEN: "FORBIDDEN",
  USER_PROFILE_NOT_FOUND: "USER_PROFILE_NOT_FOUND",
  USER_DISABLED: "USER_DISABLED",
  PROPERTY_ACCESS_DENIED: "PROPERTY_ACCESS_DENIED",
  PROPERTY_ID_REQUIRED: "PROPERTY_ID_REQUIRED",
  PROPERTY_NOT_FOUND: "PROPERTY_NOT_FOUND",
  OTHER_CHARGE_NOT_FOUND: "OTHER_CHARGE_NOT_FOUND",
  OTHER_CHARGE_ALREADY_EXISTS: "OTHER_CHARGE_ALREADY_EXISTS",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  ROOM_NOT_FOUND: "ROOM_NOT_FOUND",
  ROOM_NUMBER_ALREADY_EXISTS: "ROOM_NUMBER_ALREADY_EXISTS",
  TENANT_NOT_FOUND: "TENANT_NOT_FOUND",
  NOT_FOUND: "NOT_FOUND",
  INTERNAL_ERROR: "INTERNAL_ERROR",
});

module.exports = { ERROR_CODES };
