const { Router } = require("express");
const controller = require("../controllers/billing.controller");
const { requireAuth } = require("../middleware/auth.middleware");
const { requireRole } = require("../middleware/role.middleware");
const router = Router();
router.get("/:propertyId/billing", requireAuth, controller.list);
router.get("/:propertyId/billing/:id", requireAuth, controller.getById);
router.post("/:propertyId/billing", requireAuth, requireRole("admin"), controller.create);
router.patch("/:propertyId/billing/:id", requireAuth, requireRole("admin"), controller.update);
router.delete("/:propertyId/billing/:id", requireAuth, requireRole("admin"), controller.remove);
module.exports = { billingRouter: router };
