const { Router } = require("express");
const controller = require("../controllers/rooms.controller");
const { requireAuth } = require("../middleware/auth.middleware");
const { requireRole } = require("../middleware/role.middleware");
const router = Router();
router.get("/:propertyId/rooms", requireAuth, controller.list);
router.get("/:propertyId/rooms/:id", requireAuth, controller.getById);
router.post("/:propertyId/rooms", requireAuth, requireRole("admin"), controller.create);
router.patch("/:propertyId/rooms/:id", requireAuth, requireRole("admin"), controller.update);
router.delete("/:propertyId/rooms/:id", requireAuth, requireRole("admin"), controller.remove);
module.exports = { roomsRouter: router };
