const { Router } = require("express");
const controller = require("../controllers/tenants.controller");
const { requireAuth } = require("../middleware/auth.middleware");
const { requireRole } = require("../middleware/role.middleware");
const router = Router();
router.get("/:propertyId/tenants", requireAuth, controller.list);
router.get("/:propertyId/tenants/:id", requireAuth, controller.getById);
router.post("/:propertyId/tenants", requireAuth, requireRole("admin"), controller.create);
router.patch("/:propertyId/tenants/:id", requireAuth, requireRole("admin"), controller.update);
router.delete("/:propertyId/tenants/:id", requireAuth, requireRole("admin"), controller.remove);
module.exports = { tenantsRouter: router };
